language: go

go: "1.10"
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- ./build.sh
script:
- ./test.sh -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
