// Code generated by MockGen. DO NOT EDIT.
// Source: ./object_factory.go

// Package mock_factory is a generated GoMock package.
package mock_factory

import (
	gomock "github.com/golang/mock/gomock"
	geom "github.com/xosmig/roguelike/core/geom"
	objects "github.com/xosmig/roguelike/core/objects"
	reflect "reflect"
)

// MockObjectFactory is a mock of ObjectFactory interface
type MockObjectFactory struct {
	ctrl     *gomock.Controller
	recorder *MockObjectFactoryMockRecorder
}

// MockObjectFactoryMockRecorder is the mock recorder for MockObjectFactory
type MockObjectFactoryMockRecorder struct {
	mock *MockObjectFactory
}

// NewMockObjectFactory creates a new mock instance
func NewMockObjectFactory(ctrl *gomock.Controller) *MockObjectFactory {
	mock := &MockObjectFactory{ctrl: ctrl}
	mock.recorder = &MockObjectFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockObjectFactory) EXPECT() *MockObjectFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockObjectFactory) Create(arg0 geom.Location) (objects.GameObject, error) {
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(objects.GameObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockObjectFactoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObjectFactory)(nil).Create), arg0)
}
