name: Build and test

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          check-latest: true

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./test.sh -race -coverprofile=coverage.txt -covermode=atomic

      - name: Update the code coverage badge
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
